name: Build documentation (python 3.10)

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
        -   name: Set up Python 3.10
            uses: actions/setup-python@v5
            with:
                python-version: "3.10"
                cache: "pip"
                cache-dependency-path: "**/pyproject.toml"

        # Install docs dependencies
        -   name: Install docs dependencies
            run: |
                sudo apt-get install -y pandoc
                python -m pip install ".[docs]"


        # Test and build the docs
        -   name: Test and build docs
            run: |
                python -m sphinx -M doctest ./docs/source ./docs/_build
                python -m  sphinx -M coverage ./docs/source ./docs/_build
                python -m  sphinx -M html ./docs/source ./docs/_build
